### register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### logout
GET http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiX2lkIjoiNjRmMjU3YWMxMTg3MzI2N2FlYWU0OTM5IiwiaWF0IjoxNjkzNjAzODQzLCJleHAiOjE2OTM2MDQ3NDN9.xQESUVmE3Hc8stWDKroyqt1TMtejmXMDyDPcLNGuR1Y

### fefresh token
GET http://localhost:8080/api/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiX2lkIjoiNjRmMjU3YWMxMTg3MzI2N2FlYWU0OTM5IiwiaWF0IjoxNjkzNjAzODgyLCJleHAiOjE2OTQyMDg2ODJ9.52LkKFj2HYSShFiEqPwOs2fm1hPNZxUMglgD-8mCtMQ
