### login
POST http://localhost:{{port}}/{{prefix}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### create board
POST http://localhost:{{port}}/{{prefix}}/boards
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "test for delete"
}

### get boards for user by id from token
#GET http://localhost:8080/api/boards
GET http://localhost:{{port}}/{{prefix}}/boards
Content-Type: application/json
Authorization: Bearer {{token}}

### delete board by id with token
DELETE http://localhost:{{port}}/{{prefix}}/boards/64f2f2df51c6d19fe5c36bee
Content-Type: application/json
Authorization: Bearer {{token}}

### get board by id with token
GET http://localhost:{{port}}/{{prefix}}/boards/64f2e789cefbc1a715b48e7e
Content-Type: application/json
Authorization: Bearer {{token}}
