### Get all users without token
GET http://localhost:8080/api/users

### Get all users with token
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MzU3NzA4MX0.aFHjRb4kl3mPzLAf9drfVMu7Mh43cHwdav7-JQH1E40
